[workspace]
resolver = "2"
members = [
    "sql-types",
    "sql-expr",
    "sql-parser",
    "sql-join",
    "sql-vm",
    "sql-sys",
    "sql-record",
    "sql-vfs",
]

[workspace.package]
version = "0.10.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/t-rust-db/db-core"
