// Copyright 2026 Schuberg Philis
// SPDX-License-Identifier: Apache-2.0
//! Validates that every `mcdc__<id>__vN_<description>` tagged test
//! (db-core#111, ported from sqlite-rs's `tests/unit/mcdc_discharge_test.rs`)
//! still names a real obligation -- the failure mode this guards against is
//! silent: a code edit shifts a decision's line number, the obligation id
//! (`<file>_<line>`) changes, and the old tagged tests keep passing
//! (they're ordinary `#[test]` fns exercising real behavior) while quietly
//! no longer counting toward MC/DC discharge, because `cargo-mvl-mcdc
//! harvest` joins tagged tests to obligations by id and finds no match.
//! `make test-mcdc`'s dashboard would eventually show this as an
//! obligation stuck at 0/N vectors, but nothing forces anyone to run it
//! or read it.
//!
//! Deliberately NOT a re-run of `cargo-mvl-mcdc scan`: that requires an
//! external tool most `cargo test` runs (including CI) don't have
//! installed, so this reads the committed snapshot
//! (`tests/mcdc/obligations.json`, regenerated by `make mcdc-obligations`
//! whenever a code change shifts a decision's line) instead -- same
//! "committed evidence, regenerable on demand" split sqlite-rs uses for
//! its corpus fixtures.
//!
//! **Unlike sqlite-rs's `MCDC_FILES`, this scans all of `src/` rather
//! than a curated file list** (db-core#111's explicit scope decision --
//! no obligation should be exempted by file selection). Since there's no
//! way to glob at compile time, [`source_files`] walks the tree itself.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::string_slice,
    clippy::arithmetic_side_effects,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    reason = "test code fails fast (db-core#230); clippy.toml's allow-*-in-tests does not reach helper fns outside #[test]"
)]

use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

fn manifest_path(rel: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(rel)
}

/// Every `.rs` file under `src/`, recursively -- mirrors
/// `cargo-mvl-mcdc scan`'s own file arguments (`find src -name '*.rs'`,
/// per the Makefile's `mcdc-obligations` target) so this test's notion
/// of "everything scanned" never drifts from what actually got scanned.
fn source_files() -> Vec<PathBuf> {
    fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
        let Ok(entries) = fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                walk(&path, out);
            } else if path.extension().is_some_and(|ext| ext == "rs") {
                out.push(path);
            }
        }
    }
    let mut out = Vec::new();
    walk(&manifest_path("src"), &mut out);
    out
}

/// Every id present in the committed obligations snapshot, real or
/// compiler-void -- a tagged test naming any of these ids is at least
/// pointing at something that still exists in the source (compiler-void
/// ids just shouldn't be tagged, since they need no vectors).
///
/// Hand-rolled `"id": "..."` extraction rather than a JSON crate: this
/// crate has no dependencies by design, and `cargo-mvl-mcdc scan`'s
/// output is a flat, machine-written array where every object's `id`
/// field is a simple quoted string with no escapes -- a full parser
/// would buy nothing here.
fn known_obligation_ids() -> HashSet<String> {
    let raw = fs::read_to_string(manifest_path("tests/mcdc/obligations.json"))
        .expect("tests/mcdc/obligations.json must exist -- run `make mcdc-obligations`");
    raw.match_indices("\"id\":")
        .filter_map(|(idx, _)| {
            let rest = raw[idx + "\"id\":".len()..].trim_start();
            let rest = rest.strip_prefix('"')?;
            let end = rest.find('"')?;
            Some(rest[..end].to_string())
        })
        .collect()
}

/// Every `(id, file)` pair in the committed snapshot, in file order --
/// `id` is `<basename>_<line>`, so two files sharing a basename (e.g.
/// `src/codegen/batch.rs` and `src/vm/batch.rs`, since #192's module
/// move) can coincidentally collide on the same line number and
/// therefore the same id. `cargo-mvl-mcdc harvest` joins tagged tests to
/// obligations by id alone, so a collision silently misattributes one
/// file's discharged vectors to the other's obligation -- `make
/// test-mcdc` then reports the real one stuck at 0/N with no indication
/// why, since its own tagged tests look perfectly fine.
///
/// Hand-rolled for the same reason as [`known_obligation_ids`]: no JSON
/// dependency, and the snapshot's `"id"`/`"file"` fields are always
/// simple unescaped quoted strings in that order within one object.
fn obligation_id_file_pairs() -> Vec<(String, String)> {
    let raw = fs::read_to_string(manifest_path("tests/mcdc/obligations.json"))
        .expect("tests/mcdc/obligations.json must exist -- run `make mcdc-obligations`");
    raw.match_indices("\"id\":")
        .filter_map(|(idx, _)| {
            let after_id = raw[idx + "\"id\":".len()..].trim_start();
            let id = after_id.strip_prefix('"')?;
            let id_end = id.find('"')?;
            let id = &id[..id_end];

            let file_key = "\"file\":";
            let file_idx = raw[idx..].find(file_key)? + idx + file_key.len();
            let after_file = raw[file_idx..].trim_start();
            let file = after_file.strip_prefix('"')?;
            let file_end = file.find('"')?;

            Some((id.to_string(), file[..file_end].to_string()))
        })
        .collect()
}

/// Pre-existing cross-file collisions between `src/codegen/batch.rs` and
/// `src/vm/batch.rs` (same basename, coincidentally overlapping line
/// numbers -- both files are large and grow independently, so some
/// overlap is inevitable and not worth fighting line-by-line every time
/// either shifts). Known and accepted as of db-core#196; anything beyond
/// this fixed set is a *new* collision and must fail the test below.
const KNOWN_BATCH_COLLISIONS: &[&str] = &["batch_427", "batch_699"];

#[test]
fn every_obligation_id_in_the_snapshot_is_unique_across_files() {
    let mut files_by_id: HashMap<String, HashSet<String>> = HashMap::new();
    for (id, file) in obligation_id_file_pairs() {
        files_by_id.entry(id).or_default().insert(file);
    }

    // A single line legitimately hosts two obligations sharing one id --
    // e.g. a real multi-leaf decision alongside the tool's own
    // `compiler_void` placeholder for the same match arm. That's the
    // same file twice, not a collision; only distinct files sharing an
    // id are the failure mode this guards.
    let mut collisions: Vec<String> = files_by_id
        .into_iter()
        .filter(|(id, files)| files.len() > 1 && !KNOWN_BATCH_COLLISIONS.contains(&id.as_str()))
        .map(|(id, files)| {
            let mut files: Vec<String> = files.into_iter().collect();
            files.sort();
            format!("{id}: {}", files.join(", "))
        })
        .collect();
    collisions.sort();

    assert!(
        collisions.is_empty(),
        "these obligation ids are shared by more than one file in \
         tests/mcdc/obligations.json -- `cargo-mvl-mcdc harvest` joins tagged tests \
         to obligations by id alone, so a shared id silently misattributes discharged \
         vectors between the files (typically two files with the same basename, e.g. \
         a module move that leaves both `src/codegen/batch.rs` and `src/vm/batch.rs` \
         with a decision on the same line number). `cargo-mvl-mcdc`'s id scheme can't \
         disambiguate this on its own -- rename one file, or move one of the colliding \
         decisions to a different line, then re-run `make mcdc-obligations`:\n{}",
        collisions.join("\n")
    );
}

/// `mcdc__<id>__v<N>_<description>` -- `id` is greedy-safe here because
/// it's always followed by the literal `__v` marker before the vector
/// number, so `_` inside `id` itself (e.g. `grammar_2270`) doesn't
/// confuse the split.
fn tagged_obligation_ids(source: &str) -> Vec<String> {
    let mut ids = Vec::new();
    for (idx, _) in source.match_indices("fn mcdc__") {
        let rest = &source[idx + "fn mcdc__".len()..];
        let Some(marker) = rest.find("__v") else {
            continue;
        };
        let candidate = &rest[..marker];
        // Confirm `__v` is actually followed by digits (the vector
        // number), not coincidental text inside a longer id.
        let after = &rest[marker + "__v".len()..];
        if after.chars().next().is_some_and(|c| c.is_ascii_digit()) {
            ids.push(candidate.to_string());
        }
    }
    ids
}

#[test]
fn every_tagged_mcdc_test_names_a_real_obligation() {
    let known = known_obligation_ids();
    let mut stale = Vec::new();

    for path in source_files() {
        let Ok(source) = fs::read_to_string(&path) else {
            continue;
        };
        for id in tagged_obligation_ids(&source) {
            if !known.contains(&id) {
                stale.push(format!("{}: mcdc__{id}__...", path.display()));
            }
        }
    }

    assert!(
        stale.is_empty(),
        "these tagged MC/DC tests name obligation ids that no longer exist in \
         tests/mcdc/obligations.json -- the decision they were tagged against has \
         moved to a different line (rename the tests to the current id) or been \
         removed entirely (delete the stale tests). Regenerate the snapshot first \
         with `make mcdc-obligations` if source has changed since it was last \
         committed, then re-run this test:\n{}",
        stale.join("\n")
    );
}
